### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by anuragts** [Anurag30112003/notez#1]
Add dark mode feature
Will inherit system theme
With the dark mode toggle button

Can use the following resources -

https://tailwindcss.com/docs/dark-mode

**Comment by codegoggins** [comment]
Hey ! @Anurag30112003 
This is my very first time contributing to open source. How exactly should I contribute to this project ? I am new to Open Source , it would be great if you could help. I would like to work on this task.

**Comment by anuragts** [comment]
Hey there @codegoggins , so through this issue, you need to add a new feature, through which a person can toggle between dark mode and light mode and can also inherit the system theme. 
You can refer to the following video for reference - https://www.youtube.com/watch?v=1q5oOZE6o4c
And also read CONTRIBUTING.md and README.md to know how to contribute

**Comment by codegoggins** [comment]
@Anurag30112003 I would like to work on this feature.I would be great if you could assign the task to me

**Comment by codegoggins** [comment]
I would be great if you could assign the task to me

**Comment by Mustafa-Azad025** [comment]
hey @Anurag30112003 ,
Have You Closed The Same Issue #10 Which You Have Assigned To Me.

**Comment by flow6979** [comment]
Hey, @Anurag30112003 I am very much interested in contributing to this repository. it would be great if you assign this to me.
Thank you.

**Comment by anuragts** [comment]
Anyone can contribute to the project !!

**Comment by anuragts** [comment]
assigned to @codegoggins
